# Generated by Django 5.0 on 2024-07-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField()),
                ('lot_prefix', models.CharField(max_length=50)),
                ('username_prefix_code', models.CharField(max_length=50, unique=True)),
                ('dispatch_date_freeze', models.DateTimeField()),
                ('formal_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommonFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_value', models.TextField()),
                ('value_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.commonclient')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='features.branches')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.commonclient')),
            ],
        ),
        migrations.CreateModel(
            name='CommonClientFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.commonclient')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.commonfeature')),
            ],
            options={
                'unique_together': {('client', 'feature_id')},
            },
        ),
        migrations.CreateModel(
            name='CommonBranchDepartmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.TextField()),
                ('branch_id', models.IntegerField(verbose_name=10)),
                ('department_id', models.IntegerField(verbose_name=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.commonclient')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.commonfeature')),
            ],
            options={
                'unique_together': {('client', 'branch_id', 'department_id', 'feature')},
            },
        ),
    ]
